import Vue from 'vue'
import

{ Button, Form, FormItem, Input, Message, Container, Header, Aside, Main, Footer, Row, Col, Divider, Card, Tabs, link, Select, Option, Table, TableColumn, MenuItem, Submenu, menu, Pagination, Step, Steps, Drawer, Tooltip, Popover, Dialog, Image, Descriptions, DescriptionsItem } from 'element-ui'

Vue.component(Button.name, Button)
Vue.component(Form.name, Form)
Vue.component(FormItem.name, FormItem)
Vue.component(Input.name, Input)
Vue.component(Message.name, Message)
Vue.component(Container.name, Container)
Vue.component(Header.name, Header)
Vue.component(Aside.name, Aside)
Vue.component(Main.name, Main)
Vue.component(Footer.name, Footer)
Vue.component(Row.name, Row)
Vue.component(Col.name, Col)
Vue.component(Divider.name, Divider)
Vue.component(Card.name, Card)
Vue.component(Tabs.name, Tabs)
Vue.component(link.name, link)
Vue.component(Select.name, Select)
Vue.component(Option.name, Option)
Vue.component(Table.name, Table)
Vue.component(TableColumn.name, TableColumn)
Vue.component(MenuItem.name, MenuItem)
Vue.component(Submenu.name, Submenu)
Vue.component(menu.name, menu)
Vue.component(Pagination.name, Pagination)
Vue.component(Step.name, Step)
Vue.component(Steps.name, Steps)
Vue.component(Drawer.name, Drawer)
Vue.component(Tooltip.name, Tooltip)
Vue.component(Popover.name, Popover)
Vue.component(Dialog.name, Dialog)
Vue.component(Descriptions.name, Descriptions)
Vue.component(DescriptionsItem.name, DescriptionsItem)
Vue.component(Image.name, Image)

Vue.prototype.$message = Message
